name: GoReleaser

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ensure GITHUB_TOKEN has write permissions
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for changelog generation

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' # Should match go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # version: latest # Optionally pin to a specific GoReleaser version
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
